application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "pog123"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "58ea3d09-c947-4fdd-9430-b4fe84259f02"
  timeout_milliseconds: 10000
